version: '2.0'
services:
    PWA:
    image: drpdishant/php-laravel-mongo
    volumes:
      - ./web:/var/www/html:rw
      - ./logs/apache2:/var/log/apache2:rw
      - ./conf/php.ini:/etc/php/7.2/apache2/php.ini
      - ./conf/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ./conf/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./conf/ssl:/etc/apache2/ssl
      - ./conf/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - $HOME/.ssh:/root/.ssh
      - ./home:/root
- ./conf/ssmtp.conf:/etc/ssmtp/ssmtp.conf